In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sbn
import plotly

In [7]:
pd.read_csv("D:\Data sets Kpmg\gpt Retail.csv")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 105202: invalid start byte

In [42]:
a=open("D:\Data sets Kpmg\Superstore.csv")

In [10]:
df=pd.read_csv("D:\Data sets Kpmg\Match.csv")
df

,Match_Id,Match_Date,Team_Name_Id,Opponent_Team_Id,Season_Id,Venue_Name,Toss_Winner_Id,Toss_Decision,IS_Superover,IS_Result,Is_DuckWorthLewis,Win_Type,Won_By,Match_Winner_Id,Man_Of_The_Match_Id,City_Name,Host_Country
0,335987,18-Apr-08,2,1,1,M Chinnaswamy Stadium,2,field,0,1,0,by runs,140.0,1.0,2.0,Bangalore,India
1,335988,19-Apr-08,4,3,1,"Punjab Cricket Association Stadium, Mohali",3,bat,0,1,0,by runs,33.0,3.0,19.0,Chandigarh,India
2,335989,19-Apr-08,6,5,1,Feroz Shah Kotla,5,bat,0,1,0,by wickets,9.0,6.0,90.0,Delhi,India
3,335990,20-Apr-08,7,2,1,Wankhede Stadium,7,bat,0,1,0,by wickets,5.0,2.0,11.0,Mumbai,India
4,335991,20-Apr-08,1,8,1,Eden Gardens,8,bat,0,1,0,by wickets,5.0,1.0,4.0,Kolkata,India
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
572,981016,22-May-16,6,2,9,Shaheed Veer Narayan Singh International Stadium,2,field,0,1,0,by wickets,6.0,2.0,8.0,Raipur,India
573,981018,24-May-16,13,2,9,M Chinnaswamy Stadium,2,field,0,1,0,by wickets,4.0,2.0,110.0,Bangalore,India
574,981020,25-May-16,11,1,9,Feroz Shah Kotla,1,field,0,1,0,by runs,22.0,11.0,163.0,Delhi,India
575,981022,27-May-16,13,11,9,Feroz Shah Kotla,11,field,0,1,0,by wickets,4.0,11.0,187.0,Delhi,India
576,981024,29-May-16,2,11,9,M Chinnaswamy Stadium,11,bat,0,1,0,by runs,8.0,11.0,385.0,Bangalore,India

In [46]:
a.head()

AttributeError: '_io.TextIOWrapper' object has no attribute 'head'